version: '3.1' 

services: 
  www:  
    image: nginx 
    container_name: nginx 
    ports: 
      - 8080:80 
    volumes: 
      - ./templates:/etc/nginx/templates 
    links: 
      - "database" 
    environment:
      - NGINX_HOST=foobar.com 
      - NGINX_PORT=80 
    networks: 
      - default 
  database: 
    image: mysql:latest 
    container_name: database
    ports: 
      - 3306:3306 
    command: --default-authentication-plugin=mysql_native_password 
    environment: 
      - "MYSQL_DATABASE:database" 
      - "MYSQL_USER:admin" 
      - "MYSQL_PASSWORD:admin" 
      - "MYSQL_ROOT_PASSWORD:admin" 
    volumes: 
      - ./database/:/var/lib/mysql 
      - ./mysql:/docker-entrypoint-initdb.d 
      - ./mysql/config:/etc/mysql/conf.d 
    networks: 
      - default 
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin 
    container_name: phpmyadmin
    links: 
      - "database" 
    ports: 
      - 8000:80 
    environment: 
      - "MYSQL_USER:admin" 
      - "MYSQL_PASSWORD:admin" 
      - "MYSQL_ROOT_PASSWORD:admin" 

