services:
  rustdesk:
    image: lscr.io/linuxserver/rustdesk:latest
    container_name: rustdesk
    restart: unless-stopped
    network_mode: host
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
    volumes:
      - /home/juliano/media/software/RustDesk/config:/config
      - /home/juliano/media/software/RustDesk/logs:/logs
      - /home/juliano/media/software/RustDesk/videos:/videos
